apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd # must match argocd namespace

  # By default, deleting an application will not perform a cascade delete, thereby deleting its resources.
  # You must add the finalizer if you want this behaviour
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  syncPolicy:
    syncOptions:
      # allows skipping syncing resources that are already in the desired state
      - ApplyOutOfSyncOnly=true
      # allows using background deletion during syncing
      - PrunePropagationPolicy=background
        # Create namespace at application creation
      - CreateNamespace=true

  source:
    repoURL: git@github.com:Jojoooo1/k8s-lab.git
    targetRevision: main
    path: overlays/${ARGOCD_ENV_ENV}/infra/linkerd
    plugin:
      name: envsubst
      env:
        - name: DNS
          value: "${ARGOCD_ENV_DNS=''}"

        - name: ENV
          value: "${ARGOCD_ENV_ENV}"

        - name: PROJECT
          value: "${ARGOCD_ENV_PROJECT}"

  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
