apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-kube-prometheus-crds
  namespace: argocd

  annotations:
    argocd.argoproj.io/sync-wave: "2"

  # By default, deleting an application will not perform a cascade delete, thereby deleting its resources.
  # You must add the finalizer if you want this behaviour
  finalizers:
    - resources-finalizer.argocd.argoproj.io

# This chart is used to bypass sync error of kube-prometheus-crds

spec:
  project: default
  syncPolicy:
    syncOptions:
      - Replace=true
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/kube-prometheus-stack/crds/
    targetRevision: kube-prometheus-stack-42.2.1

  destination:
    server: "https://kubernetes.default.svc"
    namespace: observability
