# Authorization for Spring boot application to access k8s API

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole # is cluster scoped
# kind: Role # is namespace scoped
metadata:
  name: namespace-reader
  # namespace: # only use with Role since it is namespace scoped

rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]
