apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config

# Allow to use ingress with http.
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-server
    patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/command/-1"
        value: --insecure
